version: '3.7'
services:
  web:
    build: .
    command: gunicorn budget.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - base_volume:/app/static
    expose:
      - 8000
    env_file:
      - ./budget/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2967431Qwe2
      - POSTGRES_DB=budget_django
  nginx:
    build: ../nginx
    ports:
      - "1337:80"
    volumes:
      - base_volume:/app/static
    depends_on:
      - web

volumes:
  base_volume:
  postgres_data: